/// Entity identifiers for multiplayer communication.
/// These IDs are used to identify entities across client and server.
/// Unique identifier for a player in a multiplayer session.
/// Generated by the server when a player joins a room.
pub type PlayerId {
  PlayerId(String)
}

/// Unique identifier for a game room.
pub type RoomId {
  RoomId(String)
}

/// Identifier for a projectile, combining the caster's ID and a local counter.
pub type ProjectileId {
  ProjectileId(caster: PlayerId, local_id: Int)
}

/// Identifier for an enemy entity.
pub type EnemyId {
  EnemyId(Int)
}

/// Convert a PlayerId to its string representation.
pub fn player_id_to_string(id: PlayerId) -> String {
  let PlayerId(s) = id
  s
}

/// Create a PlayerId from a string.
pub fn player_id_from_string(s: String) -> PlayerId {
  PlayerId(s)
}

/// Convert a RoomId to its string representation.
pub fn room_id_to_string(id: RoomId) -> String {
  let RoomId(s) = id
  s
}

/// Create a RoomId from a string.
pub fn room_id_from_string(s: String) -> RoomId {
  RoomId(s)
}
